version: '3.7'

services:

  frontend:
    build: .
    ports:
      - 8080:80

  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/usr/app/src
    ports:
      - 3000:3000
